services:
    emsed-spring:
        container_name: emsed
        build: .
        image: emsed:latest
        depends_on:
          elasticsearch:
            condition: service_healthy
        ports:
            - 8081:8081
        environment:
          - SPRING_ELASTICSEARCH_URIS=elasticsearch-spring:9200
        networks:
            - elastic

    elasticsearch:
        container_name: elasticsearch-spring
        image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
        ports:
            - 9200:9200
        environment:
          - node.name=es01
          - xpack.security.enabled=false
          - cluster.initial_master_nodes=es01
        networks:
            - elastic
        healthcheck:
          test: curl -s http://elasticsearch-spring:9200 >/dev/null || exit 1
          interval: 10s
          timeout: 10s
          retries: 50
networks:
    elastic:
